Import('env')

env['srcs'] = []

env['srcs'].extend(Glob('*.cc'))

lib = env.StaticLibrary('alljoyn_location', env['srcs'])
shlib = env.SharedLibrary('alljoyn_location', env['srcs'])

env.Install('#dist/lib', [lib, shlib])
